/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.davidlajambe;

import org.junit.Test;
import static org.junit.Assert.*;

public class StackTest {
    @Test public void isEmptyReturnsTrue() {
        Stack classUnderTest = new Stack();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.isEmpty());
    }
}
