/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.davidlajambe.structs;

// TODO: Add EmptyStackException to handle cases where pop is called on an empty stack
public class Stack<T> {
    Node<T> top;

    public T peek() {
        return top.data;
    }

    public boolean isEmpty() {
        if (top == null) {
            return true;
        } else {
            return false;
        }
    }

    public void push(T t) {
        Node<T> new_top = new Node<T>(t);
        new_top.next = this.top;
        this.top = new_top;
    }

    public T pop() {
        if (this.top == null) {
            throw new NullPointerException("Cannot execute pop() on an empty Stack");
        }
        T removed_val = this.top.data;
        this.top = this.top.next;
        return removed_val;
    }
}
